project:
  type: book

book:
  title: "Political Data Science Hackathon (ISSSV1337)"
  subtitle: "Course Material"
  author: 
    - "Solveig Bjørkholt"
    - "Louisa Boulaziz"
    - "Eric Gabo Ekeberg Nilsen"
  contributor: 
    - "Tia Tiller"
  chapters:
    - index.qmd
    - part: "Getting ready"
      chapters: 
        - 1_Getting_ready/1_whatis.qmd
        - 1_Getting_ready/2_installing.qmd
        - 1_Getting_ready/3_writing_running_code.qmd
        - 1_Getting_ready/4_pathsfolders.qmd
        - 1_Getting_ready/5_quarto.qmd
        - 1_Getting_ready/6_github.qmd
    - part: "Tasks"
      chapters: 
        - 1_Getting_ready/06_Tasks.qmd
        - 1_Getting_ready/06_Solution.qmd
    - part: "Data wrangling and data handling"
      chapters:
        - 2_Data_wrangling/7_data-analysis.qmd
        - 2_Data_wrangling/8_data-import.qmd
        - 2_Data_wrangling/9_core_functions.qmd
        - 2_Data_wrangling/10_missings.qmd
        - 2_Data_wrangling/11_joins.qmd
    - part: "Tasks"
      chapters:
        - 2_Data_wrangling/011_Tasks.qmd
        - 2_Data_wrangling/011_Solutions.qmd
    - part: "Descriptive statistics"
      chapters: 
        - 3_Descriptives/12_measuring_concepts.qmd
        - 3_Descriptives/13_descriptives.qmd
        - 3_Descriptives/14_descriptive_display.qmd
        - 3_Descriptives/15_briefly_on_visualization.qmd
    - part: "Tasks"
      chapters: 
        - 3_Descriptives/015_Tasks.qmd
        - 3_Descriptives/015_Solution.qmd
    - part: "Data collection"
      chapters:
        - 4_Data_collection/16_data_sources.qmd
        - 4_Data_collection/17_databases_and_SQL.qmd
        - 4_Data_collection/18_webscraping.qmd
        - 4_Data_collection/19_webcrawling.qmd
        - 4_Data_collection/20_API.qmd
    - part: "Visualization"
      chapters: 
        - 5_Visualization/21_graphs_with_ggplot.qmd
        - 5_Visualization/22_graphs_with_plotly.qmd
        - 5_Visualization/23_dashboards_and_shiny.qmd
    - part: "Text as data"
      chapters:
        - 6_Text_as_data/24_text_manipulation.qmd
        - 6_Text_as_data/25_text_preprocessing.qmd
        - 6_Text_as_data/26_text_tokenization.qmd
        - 6_Text_as_data/27_text_vectorization.qmd
        - 6_Text_as_data/28_topic_modelling.qmd
    - part: "Introduction to machine learning and statistics"
      chapters:
        - 7_Modelling/29_introduction_to_ml.qmd
        - 7_Modelling/30_inference.qmd
    - part: "Machine learning methods"
      chapters:
        - 7_Modelling/SL_regression/31_regression.qmd
        - 7_Modelling/SL_classification/32_classification.qmd
        - 7_Modelling/33_unsupervised_ml.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: source

