project:
  type: book

book:
  title: "ISSSV1337 - Course Material"
  author: "Solveig Bjørkholt"
  chapters:
    - index.qmd
    - part: "Getting ready"
      chapters: 
        - 1_Getting_ready/1_whatis.qmd
        - 1_Getting_ready/2_installing.qmd
        - 1_Getting_ready/3_writing_running_code.qmd
        - 1_Getting_ready/4_pathsfolders.qmd
        - 1_Getting_ready/5_quarto.qmd
        - 1_Getting_ready/6_github.qmd
    - part: "Data wrangling and data handling"
      chapters:
        - 2_Data_wrangling/7_data-analysis.qmd
        - 2_Data_wrangling/8_data-import.qmd
        - 2_Data_wrangling/9_core_functions.qmd
        - 2_Data_wrangling/10_missings.qmd
        - 2_Data_wrangling/11_joins.qmd
    - part: "Descriptive statistics"
      chapters: 
        - 3_Descriptives/12_measurement_level.qmd
        - 3_Descriptives/13_descriptives.qmd
        - 3_Descriptives/14_descriptive_display.qmd
        - 3_Descriptives/15_briefly_on_visualization.qmd


bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: source

