project:
  type: book

book:
  title: "ISSSV1337 - Course Material"
  author: "Solveig Bjørkholt"
  chapters:
    - index.qmd
    - part: "Getting ready"
      chapters: 
        - 1_Getting_ready/1_whatis.qmd
        - 1_Getting_ready/2_installing.qmd
        - 1_Getting_ready/3_writing_running_code.qmd
        - 1_Getting_ready/4_pathsfolders.qmd
        - 1_Getting_ready/5_rmarkdown.qmd
        - 1_Getting_ready/6_github.qmd
    - part: "Data wrangling and data handling"
      chapters:
        - 2_Data_wrangling/7_data-analysis.qmd
        - 2_Data_wrangling/8_data-import.qmd
        - 2_Data_wrangling/9_core_functions.qmd
        - 2_Data_wrangling/10_missings.qmd
        - 2_Data_wrangling/13_joins.qmd
    - part: "Descriptive statistics"
      chapters: 
        - 3_Descriptives/11_descriptives.qmd
        - 3_Descriptives/12_descriptive_display.qmd



bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

